# Default configuration settings for merging
# Please create your own config files instead of modifying this one directly!

validation:
    batch_size: 2 # Number of files to query metacat about at once
    allow_missing: false
    allow_duplicates: false
    checksums:
      - "adler32"   # Adler32 should be the default checksum
    consistency:   # These keys must be the same for all files
      - "core.run_type"
      - "core.file_type"
      - "core.file_format"
      - "core.data_tier"
      - "core.data_stream"
      - "core.application.name"
      - "dune.campaign"
      - "dune.requestid"
      - "dune.config_file"          # Not checked in old merging
      - "core.application.version"  # Not checked in old merging
    types:   # These keys must have the correct types
        "core.application.family":  'str'
        "core.application.name":    'str'
        "core.application.version": 'str'
        "core.data_stream":         'str'
        "core.data_tier":           'str'
        #"core.end_time":            'float'
        "core.event_count":         'int'
        "core.events":              'list'
        "core.file_content_status": 'str'
        "core.file_format":         'str'
        "core.file_type":           'str'
        "core.first_event_number":  'int'
        "core.last_event_number":   'int'
        "core.run_type":            'str'
        "core.runs":                'list'
        "core.runs_subruns":        'list'
        #"core.start_time":          'float'
        "dune.daq_test":            'str'
        #"dune.config_file":         'str'
        "dune_mc.gen_fcl_filename": 'str'
        "dune_mc.geometry_version": 'str'
        "retention.status":         'str'
        "retention.class":          'str'
    required:   # These keys must have a valid value
        "core.run_type":
          - "test"
          - "protodune-sp"
          - "protodune-dp"
          - "iceberg"
          - "np04_vst"
          - "hd-coldbox"
          - "vd-coldbox"
          - "vd-coldbox-bottom"
          - "vd-coldbox-top"
          - "protodune-hd"          # old script
          - "hd-protodune"
          - "vd-protodune"
          - "vd-protodune-pds"
          - "dc4-vd-coldbox-bottom"
          - "dc4-vd-coldbox-top"
          - "dc4-hd-protodune"      # old script
          - "neardet"
          - "neardet-lar"
          - "neardet-2x2"           # old script
          - "neardet-2x2-lar"       # old script
          - "neardet-2x2-lar-charge"
          - "neardet-2x2-lar-light"
          - "neardet-2x2-minerva"   # old script
          - "fardet"                # old script
          - "fardet-sp"             # old script
          - "fardet-hd"             # old script
          - "fardet-vd"             # old script
          - "311"                   # old script
          - "311_dp_light"          # old script
        # Other keys from metacat
          - "ehn1-beam-np04"
          - "physics"
        # - "justin-tutorial"
        "core.file_type":
          - "mc"
          - "detector"
          - "importedDetector"      # old script, minerva
        # Other keys from metacat
        # - "unknown"
        # - "test-data"
        # - "binary"
        # - "photon_detector"
        # - "test"
        # - "dc1simdaq"
        # - "data"
        "core.data_stream":
          - "test"
          - "out1"
          - "out2"
          - "noise"
          - "cosmics"
          - "calibration"
          - "physics"
          - "commissioning"
          - "pedestal"
          - "study"
          - "trigprim"
          - "pdstl"
          - "linjc"
          - "numib"
          - "numip"
          - "numil"
        # Other keys from metacat
          - "g4beamline"
        "core.data_tier":
          - "simulated"
          - "raw"
          - "hit-reconstructed"
          - "full-reconstructed"
          - "generated"
          - "detector-simulated"
          - "root-tuple"
          - "root-hist"
          - "decoded-raw"
          - "pandora-info"
          - "reco-recalibrated"
          - "root-tuple-virtual"
          - "trigprim"
          - "sliced"              # old script
          - "dc1input"            # old script
          - "binary-raw"          # old script
          - "sam-user"            # old script
        # Other keys from metacat
        # - "test"
        # - "stage1"
        # - "stage2"
        "core.file_format":
          - "root"
          - "artroot"
          - "binary"
          - "rootntuple"
          - "hdf5"
          - "tar"
    optional:
        "all":  # These keys are optional for all files
            - "core.events"
            - "dune.daq_test"
        "mc":  # These keys are specific to MC files
            - "dune_mc.gen_fcl_filename"
            - "dune_mc.geometry_version"
        "root-tuple": &tuple_optionals
            - "core.event_count"
            - "core.first_event_number"
            - "core.last_event_number"
        "root-tuple-virtual": *tuple_optionals
        "raw": &raw_optionals
            - "dune.config_file"
            - "dune_mc.gen_fcl_filename"
            - "dune_mc.geometry_version"
            - "core.application.family"
            - "core.application.name"
            - "core.application.version"
        "binary-raw": *raw_optionals
        "trigprim": *raw_optionals
    fixes:  # Fix common issues with the metadata
        keys:       # Misspelled keys
            "DUNE.requestid": "dune.requestid"
        missing:    # Default values for missing keys
            "core.file_content_status": "good"
            "retention.status": "active"
            "retention.class": "unknown"
        # Misspelled values
        "core.data_tier":
            "pandora_info": "pandora-info"
        "core.data_stream":
            "Test": "test"
            "Cosmics": "cosmics"
            "pdstl": "pedestal" # Not completely sure about this one
        "core.file_format":
            "tfile": "root"     # 

sites:
    max_distance: 1000        # Distances range from 0 to 101
    nearline_distance:        # Extra distance to account for staging
        default:        100   # Default distance for all RSEs
        "FNAL_DCACHE":  10
    allowed_sites:
      - "US_FNAL-FermiGrid"
      - "CERN"

merging:
    method: auto        # Can be auto or a specific method from the list below
    target_mode: size   # Options: size, count
    target_size: 20     # Target size (in GB) or number of files
    equalize: true      # Try to equalize the size of the merged files
    chunk_min: 5        # Minimum number of files to merge at once
    chunk_max: 100      # Maxiumum number of files to merge at once
    metadata:   # Special handling for metadata keys, options are:
        # unique   only save key if all values are the same
        # all      save a list of all values
        # min      save the minimum value
        # max      save the maximum value
        # sum      save the sum of all values
        # union    save the union of all values
        # ~        ignore the key
        default:                    unique
        "core.first_event_number":  min
        "core.last_event_number":   max
        "core.event_count":         sum
        "core.events":              union
        "core.runs":                union
        "core.runs_subruns":        union
        "core.start_time":          ~
        "core.end_time":            ~
        "Offline.options":          ~
        "Offline.machine":          ~
        overrides: # Set keys to specific values
            "retention.status":     "active"
    methods:
        "hadd":
            file_format:
              - "root"
              - "rootntuple"
              - "tfile"
            ext: ".root"
        "lar":
            file_format:
              - "artroot"
            ext: ".root"
        "hdf5":
            file_format:
              - "hdf5"
            ext: ".hdf5"
        "tar":
            file_format:
              - "binary"
              - "tar"
              - "unknown"
            output_format: "tar"
            ext: ".tar"

output:
    name: "{core.run_type}_{dune.campaign}_{dune.config_file}_{core.application.name}_merged_{timestamp}"
    #name: "{core.run_type}_{core.file_type}_{dune.campaign}_{core.data_stream}_{dune.config_file}_{core.data_tier}_merged_{timestamp}"
    grandparents: false # List the parents of the input files as the parents of the merged file
    abbreviations:
        "core.run_type":
            "protodune-sp":             "pd-sp"
            "protodune-dp":             "pd-dp"
            "hd-coldbox":               "cb-hd"
            "vd-coldbox":               "cb-vd"
            "vd-coldbox-bottom":        "cb-vd-b"
            "vd-coldbox-top":           "cb-vd-t"
            "protodune-hd":             "pd-hd"
            "hd-protodune":             "pd-hd"
            "vd-protodune":             "pd-vd"
            "vd-protodune-pds":         "pd-vd-pds"
            "vd-protodune-arapucas":    "pd-vd-arapucas"
            "dc4-vd-coldbox-bottom":    "cb-dc4-vd-b"
            "dc4-vd-coldbox-top":       "cb-dc4-vd-t"
            "dc4-hd-protodune":         "pd-dc4-hd"
            "neardet":                  "nd"
            "neardet-lar":              "nd-lar"
            "neardet-2x2":              "nd-2x2"
            "neardet-2x2-lar":          "nd-2x2-lar"
            "neardet-2x2-lar-charge":   "nd-2x2-lar-charge"
            "neardet-2x2-lar-light":    "nd-2x2-lar-light"
            "neardet-2x2-minerva":      "nd-2x2-minerva"
            "fardet":                   "fd"
            "fardet-sp":                "fd-sp"
            "fardet-hd":                "fd-hd"
            "fardet-vd":                "fd-vd"
            "fardet-dp":                "fd-dp"
            "fardet-moo":               "fd-moo"
            "311_dp_light":             "311-dp-light"
            "physics":                  "phys"
            "protodune":                "pd"
            "protodune-vst":            "pd-vst"
        "core.file_type":
            "detector":                 "det"
            "importedDetector":         "imp-det"
            "binary":                   "bin"
            "photon_detector":          "photo-det"
        "core.data_stream":
            "calibration":              "calib"
            "physics":                  "phys"
            "commissioning":            "comm"
            "pedestal":                 "pdstl"
            "g4beamline":               "g4"
        "core.data_tier":
            "simulated":                "sim"
            "hit-reconstructed":        "hit-reco"
            "full-reconstructed":       "full-reco"
            "generated":                "gen"
            "detector-simulated":       "det-sim"
            "root-tuple":               "r-tuple"
            "root-hist":                "r-hist"
            "decoded-raw":              "dec-raw"
            "pandora-info":             "pandora"
            "reco-recalibrated":        "reco-recal"
            "root-tuple-virtual":       "r-tuple-v"
            "binary-raw":               "binary"
            "sam-user":                 "sam"
        "core.file_format":
            "artroot":                  "art"
            "binary":                   "bin"
            "rootntuple":               "tuple"
