# Default configuration settings for merging
# Please create your own config files instead of modifying this one directly!

inputs:
    mode: dids              # Options: query, dids, files
    namespace: "usertests"  # Default namespace for local input files
    inputs: []              # List of inputs
    search_dirs: []         # List of directories to search for metadata files

output:
    mode: justin      # Options: dids, replicas, pfns, local, justin
    dir: "/pnfs/dune/scratch/users/${USER}/merge_test" # Directory to save local merged files
    namespace: "usertests" # Optionally specify a namespace different from the parents
    name: "{core.run_type}_{dune.campaign}_{dune.config_file}_{core.application.name}"
    #name: "{core.run_type}_{core.file_type}_{dune.campaign}_{core.data_stream}_{dune.config_file}_{core.data_tier}"
    grandparents: false # List the parents of the input files as the parents of the merged file

validation:
    batch_size: 100   # Number of files to query metacat about at once
    fast_fail: True   # Stop processing files as soon as one batch fails validation
    skip:             # Continue processing files even if some fail validation
        missing:      false # Skip files with missing metadata
        duplicate:    false # Skip duplicated files
        unreachable:  false # Skip files that are not accessible
        invalid:      false # Skip files with invalid metadata
        inconsistent: false # Skip files with inconsistent metadata
    checksums:
      - "adler32"     # Adler32 should be the default checksum
    consistent:       # These metadata keys must be the same for all input files
      - "core.run_type"
      - "core.file_type"
      - "core.file_format"
      - "core.data_tier"
      - "core.data_stream"
      - "core.application.name"
      - "dune.campaign"
      - "dune.requestid"
      - "dune.config_file"          # Not checked in old merging
      - "core.application.version"  # Not checked in old merging
    required:       # These metadata keys must be present in all input files
    optional:       # These metadata keys are optional (overrides required and conditional keys)
      - "dune_mc.geometry_version"

sites:
    local_site: "US_FNAL-FermiGrid"   # Local site name
    allowed_sites:                    # Sites where merging is allowed
      - "US_FNAL-FermiGrid"
      - "CERN"
    max_distance: 1000                # Distances range from 0 to 101
    nearline_distance:                # Extra distance to account for staging
        default:        100           # Default distance for all RSEs
        "FNAL_DCACHE":  10

merging:
    method: auto        # Can be auto or a specific method from the list below
    target_mode: size   # Options: size, count
    target_size: 10     # Target size (in GB) or number of files
    equalize: true      # Try to equalize the size of the merged files
    chunk_min: 5        # Minimum number of files to merge at once
    chunk_max: 100      # Maxiumum number of files to merge at once
    methods:
        "hadd":
            file_format:
              - "root"
              - "rootntuple"
              - "tfile"
            ext: ".root"
        "lar":
            file_format:
              - "artroot"
            ext: ".root"
            fcl: "artcat.fcl"
        "hdf5":
            file_format:
              - "hdf5"
            ext: ".hdf5"
        "tar":
            file_format:
              - "binary"
              - "tar"
              - "unknown"
            output_format: "tar"
            ext: ".tar"
    